[package]
name = "matrust"
version = "0.1.0"
authors = ["Adam Budziak <adam.budziak.ext@nokia.com>"]
edition = "2018"

[dependencies]
nalgebra = "0.18.0"
regex = "1"
itertools = "0.8.0"
openssl = { version = "0.10", features = ["vendored"]}
hex = "0.3.2"
rayon = "1.0.3"
rug = "1.4.0"
rand = "0.6"
